<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kalai" failures="2" tests="8" name="Test" time="0.166" errors="0" timestamp="2023-08-12T15:53:38 IST">
  <testcase classname="org.retryanalyse.ClassA" name="test1" time="0.017"/>
  <testcase classname="org.retryanalyse.ClassA" name="test2" time="0.003"/>
  <testcase classname="org.retryanalyse.ClassA" name="test3" time="0.018">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="org.retryanalyse.ClassA" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="org.retryanalyse.ClassA" name="test3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.retryanalyse.ClassA.test3(ClassA.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="org.retryanalyse.ClassA" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="org.retryanalyse.ClassA" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="org.retryanalyse.ClassA" name="test4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.retryanalyse.ClassA.test4(ClassA.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
